VividCortex/angular-recaptcha

src/directive.js
src/service.js

#29 If the directive is within a named form or ngForm (has the form controller) it will now set validation on that form depending on if the box is checked or not. Using standard form validation can help prevent bad submissions.
#28 onExpire will be fired when the captcha's session expires (from testing, it was always two minutes, thus a two minute timeout).
#27 ngModel will now be populated with the response value if it is on the element (And it will become "" when the session expires (mimicking the hidden textarea that is injected by recaptcha (use recaptcha for full page form submissions)))
\+ WidgetId is now accessible in the onSuccess callback
\+ Slight clean up of unused injections

Feat(validation): Added validation if within ngForm. + Slight clean-up.

---

bower.json

The module is registered to Bower as "angular-recaptcha", but the {{bower.json}} had name of {{vc-angular-recaptcha". This fixes that. If you prefer to register to Bower as "vc-angular-recaptcha" instead or as well, that is also an option.

rename in bower.json

---

src/directive.js

There was a dependency on jQuery that was accidentally added.  This removes the dependency by utilizing native browser `document.querySelectorAll()`.
This also DRYs up that call by moving it to a function that can be called where needed.

Fix(directive): remove jquery dep

---

src/directive.js

Hey guys, not sure why that line was written that way, here’s how i think it could be improved.
querySelectorAll is not available in $document.
Closes #54

querySelectorAll is available in document but not in $document

---

src/directive.js

The current angular-recaptcha directive does not allow for modification of the tabindex attribute. This allows for that customization.

Add ability to customize tabindex attribute

---

src/directive.js

This fixes a security error after reloading the captcha.
```
Uncaught SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a frame with origin "https://xxx.com". Protocols, domains, and ports must match.
```
Fixes #62, fixes #63

Remove cleanup after creating the captcha element

---

src/directive.js

When the directive is removed/destroyed, as would be the case when using an `ng-if,` then this PR makes sure that any enclosing forms validity is reset to a state as if the directive was never included.
Specifically we remove the validity record and stop the session timeout from completing (which would have forced the validity to false after 2 mins).

Tidy up the validity state on $destroy.

---

README.md
src/directive.js

Adds type support through the type attribute, which just gets passed to
reCaptcha.  Possible values are `'audio'` and `'image'` (per reCaptcha
docs). README was also update to show this attribute.

Add type support

---

README.md
src/directive.js

Resolves #96 by adding and documenting the required attribute.
When require is `false` or is a scoped variable which is `false`,
the form validation will be removed.
This is opt out to prevent a breaking change and usually the validation is
preferred.
This change also includes the changes to use the recaptcha expired callback as they would have conflicted if made separately.

Add required to opt out of validation

---

README.md

Updated the README to include information about ng-model as using it
over manually/programmatically trying to get the reCaptcha response is
easier and will lead to less issues.
This feature has been there for a while, but there are a ton of issues around people trying to get the reCaptcha response using `getResponse()`. `getResponse()` requires management of the widgetId in most cases (to be done right), as navigating a SPA generates a new widget for each time a route with a widget is loaded. `ng-model` does not require the developer to do anything special and works more "the angular way" ( :unamused: )

Update docs to include ng-model

---

README.md
src/directive.js
src/service.js

Resolves #98 by changing  the service to a service provider which allows the user to set default values for the site key, theme, stoken, size, and type. These
defaults can be overridden by setting the values on individual instances
of the directive.
The key validation has been moved out of the directive and into the
service since now the directive does not require a key (as it can use the
default defined in the provider during the config by the user).

Change service to service provider

---

README.md
src/service.js

Resolves #25 by adding the ability to set the name of the function that is
used as the onload callback.
Also added documentation.
_This commit is on top of the commit which adds the service provider as the
service provider is needed for this to work._

Add ability to set onload function name

---

src/directive.js
src/service.js

Resolves #69 and #111. When the service triggers a reset, the directive associated with the
widgetid being reset will clear the response on the model and mark the
element as invalid (if validation is enabled).
This uses pub/sub to allow the service to notify the directive of the reset. There are several other ways to do this but this was more simple.

Reset directive validation when reCaptcha is reset

---

.gitignore
.travis.yml
Gruntfile.js
README.md
bower.json
karma.conf.js
package.json
tests/directive_test.js
tests/service_test.js

_Note: This is based on #49 and the 99.999% of the work has been done by @ericmdantas_
The project has been setup on Travis-CI and runs the specs on Chrome and Firefox.
Once this gets merged we can go ahead and release a major version with the latest changes available in the master branch.
**TODO:**
Finish integration with [Coveralls](https://coveralls.io).

Test suite

---

Gruntfile.js

Minifiers like [uglifyjs](https://github.com/mishoo/UglifyJS2#keeping-copyright-notices-or-other-comments) and [closure compiler](https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-license) interpret the `@license` tag and preserve the license in the minified output. This makes it easier to comply with the MIT license (and most others) which requires:
> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

Make it easier to preserve license after minification

---

.travis.yml

I noticed the coverage badge in the README and that a grunt coverage task was set up... this just tell travis to report the coverage after it runs the tests.

chore(coverage): report coverage on CI build

---

README.md
karma.conf.js
src/service.js
tests/provider.driver.js
tests/provider_test.js
tests/service.driver.js
tests/service_test.js

No need to load recaptcha script on the html if one of the views uses it.
Load it on demand when vcRecaptchaService is injected in the first time.
closes #175

Improvement: Generate recaptcha script on demand. closes #175

---

demo/usage.html

Because of Changelog
"3.0.0 - Removed the need to include the Google recaptcha api."

Remove include script in <head> of google api

---

src/directive.js
src/service.js
tests/provider_test.js
tests/service_test.js

This should fix the following issue: #186

Added support for the new Invisible reCaptcha badge attribute and execute() API method.

---

src/service.js
tests/service.driver.js
tests/service_test.js

There is a race condition that can happen if google <script> is already in the page when vcRecaptcha is initializing and $window.grecaptcha is not yet defined.
In this case, vcRecaptchaApiLoaded is never called because google recaptcha script takes the first script onLoad callback.
PR is needed to check if google recaptcha script is already in the DOM, and wait for $window.grecaptcha to be defined (when script will be loaded).
My first idea was to parse the script url to override the onLoad call, but onLoad is not mandatory, so we have to wait for the script to load with an interval. Adding script.onload would not work in all browsers.

recaptcha script could already be in the DOM and not downloaded yet

---

src/service.js
tests/directive_test.js

Recaptcha may generate site keys with more than 40 characters now, so the length check is outdated and can throw unexpected errors in such cases.

Remove site key length check

---

src/service.js
tests/service_test.js

Instead of checking for the variable `grecaptcha` to be defined, now we check for the `grecaptcha.render` function to be defined and to be a function.
It has happened in Firefox(due to browser cache), that sometimes the `grecaptcha` variable is already defined, but as empty object, causing the library to fail due to the lack of the render function.
Fixes #224

Check for grecaptcha.render function availability

---

src/service.js

After May 4 one could get "render is not a function" error message.
This patch fixes a bug.

Wait for render function to be ready

---

src/directive.js
tests/directive_test.js

feat(vcRecaptcha): add error callback support
